FizzBuzz.Web/Controllers/FizzBuzzController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FizzBuzz.Web.Repositories;
using FizzBuzz.Model;
using FizzBuzz.Web.Helpers;
namespace FizzBuzz.Web.Controllers
{
    public class FizzBuzzController : Controller
    {
        private IFizzBuzzRepository _fizbuzz;

        #region Constructor
        public FizzBuzzController(IFizzBuzzRepository fizzBuzz)
        {
            this._fizbuzz= fizzBuzz;
        }
        #endregion

        #region public methods
        
        public ActionResult Index()
        {
            return View(Constants.ViewName.index);
        }

        public PartialViewResult GetCalculatedResult(int val)
        {
            //Submit the data to API
            this._fizbuzz.Submit(val);
            //calculate the input val
            IList<Quiz> quizList = this._fizbuzz.GetResult(val);
            //Return partial view
            //return PartialView("~/Views/FizzBuzz/_Status.cshtml", quizList);
            return PartialView(Constants.ViewName.searchResult, quizList);
        }
        #endregion
    }
}

FizzBuzz.Web/Views/FizzBuzz/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Welcome to Fizz Buzz </h2>

<p>
    Enter number between 1 to 1000 : <input id="txtNumber" name="txtNumbar" class="text-box" />
    <input type="button" name="submit" id="btnSubmit" value="Submit" onclick="Calculate();">
    <div id="divResult">

    </div>

</p>

FizzBuzz.Web/Views/FizzBuzz/_SearchResult.cshtml
@using FizzBuzz.Web.Helpers
@model IEnumerable<FizzBuzz.Model.Quiz>


<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Fizz or Buzz")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            @if (item.QuizName.ToLowerInvariant() == Constants.fizz.ToLowerInvariant())
            {
                <td class="text-blue">
                    @Html.DisplayFor(modelItem => item.QuizName)
                </td>
            }
            else if (item.QuizName.ToLowerInvariant() == Constants.buzz.ToLowerInvariant())
            {
                <td class="text-green">
                    @Html.DisplayFor(modelItem => item.QuizName)
                </td>
            }
            else
            {
                <td>
                    @Html.DisplayFor(modelItem => item.QuizName)
                </td>
            }
        </tr>
    }

</table>
<h3>Success fully added</h3>

FizzBuzz.Web/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    
    
    

    @Styles.Render("~/Content/css")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "FizzBuzz", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/script")

    @RenderSection("scripts", required: false)
</body>
</html>